--- #YAML:1.0
name:                Email-Folder-POP3
version:             1.012
abstract:            Email::Folder Access to POP3 Folders
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Email::Folder:                 0.84
    Email::FolderType::Net:        1.02
    Net::POP3:                     2.28
    Test::More:                    0.47
    URI:                           1.35
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Casey West <casey@geeknest.com>
